# post.comments.enable: true
comments:  # 评论
    enable: true  # 开启评论
    type: utterances
# utterances
# You can install utterances with https://utteranc.es/ and generate your configuration
utterances: 
  repo: zhaobokai341/zhaobokai341.github.io
  issue_term: pathname
  label: #
  theme: github-light
  crossorigin: anonymous
